name: Lint Code

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.3
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Install dependencies
      run: poetry install
      
    - name: Run Black formatter check
      run: poetry run black --check jsonshiatsu tests examples
      
    - name: Run isort check (non-blocking)
      run: poetry run isort --check-only jsonshiatsu tests examples || echo "Import sorting differences found but continuing..."
      continue-on-error: true